<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => Str::uuid(),
                'name' => 'علی',
                'family' => 'رحیمی',
                'username' => 'doctor_nutrition',
                'email' => 'ali.rahimi@example.com',
                'phone' => '09120000001',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'متخصص تغذیه و رژیم درمانی',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'سارا',
                'family' => 'مرادی',
                'username' => 'mechanic_car',
                'email' => 'sara.moradi@example.com',
                'phone' => '09120000002',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'تعمیرکار خودرو با ۱۰ سال تجربه',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'رضا',
                'family' => 'کریمی',
                'username' => 'teacher_english',
                'email' => 'reza.karimi@example.com',
                'phone' => '09120000003',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'مدرس زبان انگلیسی و آیلتس',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'مریم',
                'family' => 'اصفهانی',
                'username' => 'psychologist',
                'email' => 'maryam.esfahani@example.com',
                'phone' => '09120000004',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'روانشناس بالینی و مشاور خانواده',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'حسین',
                'family' => 'احمدی',
                'username' => 'fitness_trainer',
                'email' => 'hossein.ahmadi@example.com',
                'phone' => '09120000005',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'مربی بدنسازی و فیتنس',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'الهام',
                'family' => 'جعفری',
                'username' => 'painter_artist',
                'email' => 'elham.jafari@example.com',
                'phone' => '09120000006',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'نقاش و هنرمند تجسمی',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'محمد',
                'family' => 'شیرازی',
                'username' => 'it_specialist',
                'email' => 'mohammad.shirazi@example.com',
                'phone' => '09120000007',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'کارشناس فناوری اطلاعات و شبکه',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'فاطمه',
                'family' => 'کاظمی',
                'username' => 'makeup_artist',
                'email' => 'fatemeh.kazemi@example.com',
                'phone' => '09120000008',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'آرایشگر و متخصص زیبایی',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'امیر',
                'family' => 'نجفی',
                'username' => 'lawyer_expert',
                'email' => 'amir.najafi@example.com',
                'phone' => '09120000009',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'وکیل پایه یک دادگستری',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'لیلا',
                'family' => 'حسینی',
                'username' => 'chef_home',
                'email' => 'leila.hosseini@example.com',
                'phone' => '09120000010',
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'bio' => 'سرآشپز و مدرس آشپزی خانگی',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
